### ISSUE TITLE
FMT command lint all swift dependency

### ISSUE THREAD

**Issue by forgr-owner** [ionic-team/create-capacitor-plugin#119]
When running fmt, the swift lint lint all dev deps including any package added as dependency white thoses files are not commited.
I tried to upgrade the ingore list but couldn't find a solution

**Comment by jcesarmobile** [comment]
are you using latest version? which version of `@ionic/swiftlint-config` is being installed?

0.18.0 should be installing `@ionic/swiftlint-config` 2.0.0, which should have fixed those problems.

Can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response

**Comment by forgr-owner** [comment]
Some of our repo work properly and some not without clear issue why.
Here is one exemple not working : https://github.com/Cap-go/capacitor-updater

![Image](https://github.com/user-attachments/assets/f1313bca-dc0e-48ff-89a4-7aa98f3a8380)
it does lint all libs code
