### ISSUE TITLE
Can I have only one specific platform for a plugin?

### ISSUE THREAD

**Issue by evangunawan** [ionic-team/create-capacitor-plugin#62]
Hello! So I am developing a plugin, which I think it supports only on Android platform.

Is there any way to generate a plugin with one or specific platform?
And can I just delete the `ios` directory and modify the plugin's package.json?

Thank you very much!

**Comment by thomasvidas** [comment]
You can just delete the `ios` directory, remove the iOS dependencies from your `package.json`, and remove the `.podspec` file as well and it would work fine
