### ISSUE TITLE
Running npx @capacitor/cli plugin:generate gives "removed" errror

### ISSUE THREAD

**Issue by vilasp** [ionic-team/create-capacitor-plugin#63]
As the title explains, running `npx @capacitor/cli plugin:generate` gives the following error,
![image](https://user-images.githubusercontent.com/5450557/123631890-8f99c980-d817-11eb-90ce-f04b230ae28e.png)

Are we not suppose to be able to create v2 plugins anymore? Running the command suggested by the output will create a v3 template with v3 dependencies

**Comment by thomasvidas** [comment]
You can use `npx @capacitor/cli@2 plugin:generate` to build a capacitor 2 plugin. Your error happens because `npx` will pull the local package you have in your project _or_ the latest available one on npm. I'll update the docs to be a bit more clear.
