### ISSUE TITLE
No such module "MapboxMaps" iOS

### ISSUE THREAD

**Issue by f4bb1o** [ionic-team/create-capacitor-plugin#70]
Hi,
i'm trying to develop a plugin for iOS with Mapbox, but i always receive the error No such module "MapboxMaps" when i try to run the app. I included the pods everywhere but the error is still there
With Android all works well.
Any suggestion?

Thanks

**Comment by jcesarmobile** [comment]
Can you provide your plugin repository?

**Comment by jcesarmobile** [comment]
closing due to the lack of response
