### ISSUE TITLE
feat: allow plugin to self run cap sync

### ISSUE THREAD

**Issue by riderx** [ionic-team/create-capacitor-plugin#77]
when you install a plugin you always want to cap sync, why not add this as postinstall script ?
then user will never forget to sync, i understand it can have some downside, that why i open the question here.
Good or bad idea ?

**Comment by jcesarmobile** [comment]
I don't think it's a good idea because on a fresh cloned app if you run `npm install` and all the plugins have the postinstall script all of them will then run cap sync while you probably only want to run it once.
