### ISSUE TITLE
Choosing older capacitor version

### ISSUE THREAD

**Issue by filipRisteski** [ionic-team/create-capacitor-plugin#87]
I need to create a Capacitor 4 plugin. I poked around files, but I couldn't find any option to indicate which Capacitor version I want. I am fine going with 5, but in our Ionic app many other capacitor plugins we are using are still not compatible with version 5, so I specifically need to go with 4. 

Am I missing something here? 

I also tried to use the `capacitor/cli@4 plugin:generate` but it was removed long time ago from cli, so no luck there too.

**Comment by jcesarmobile** [comment]
You should be able to create a plugin for an older Capacitor version if you use the package version that added support for the Capacitor version you want to use, in example for Capacitor 4 you should be able to use `npx @capacitor/create-plugin@0.9.0`
