### ISSUE TITLE
Update dependencies to newest versions

### ISSUE THREAD

**Issue by alan3602k** [ionic-team/create-capacitor-plugin#89]
hello Ionic Team 👋

Any chance to update the dependencies of the project?
current versions seem a bit behind compared to the [android-template](https://github.com/ionic-team/capacitor/tree/main/android-template)

Moving to these versions would be very useful:
- Update capacitor/core to **5.6.0**
- Update the Gradle plugin to **8.2.1**
- Swap compileSdkVersion with compileSdk
- Set compileSdk and targetSdkVersion to **34**

Thanks!

**Comment by alan3602k** [comment]
@jcesarmobile

**Comment by rricamar** [comment]
This would be nice, some versions seem to be updated; not only Capacitor but also `prettier`, `eslint`, etc.

Maybe it would be nice to have a little release with all these dependencies updated 🙏

**Comment by johnborges** [comment]
Yes. It would be helpful to get this supported with Cap v6 coming.
